chore: comment and organize gradle.properties
uPortal-Project/uPortal-start pull request #530
Opened 2021-08-16 19:52 UTC by bjagg

##### Checklist

-   [ ] the [individual contributor license agreement][] is signed
-   [ ] commit message follows [commit guidelines][]

##### Description of change

It was unclear where version numbers were used which led to changes that broken the build/portal. Comments and re-organization hopefully clarifies this.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

2021-08-16 19:55 UTC, ChristianMurphy approved these changes

2021-08-16 21:26 UTC, jonathanmtran requested changes

2021-08-16 21:26 UTC, jonathanmtran commented on overlays/cas/build.gradle
> +    testCompile group: 'org.springframework', name: 'spring-jdbc', version: ${casSpringVersion}
`${casSpringVersion}` needs to be surrounded by double quotes

2021-08-16 22:15 UTC, jonathanmtran approved these changes

2021-08-17 09:19 UTC, jgribonvald approved these changes
Thx @bjagg it will help to understand !

2021-08-17 15:42 UTC, merged