UPSE-285: address Gradle file issue which seems more prominent when u…
uPortal-Project/uPortal-start pull request #613
Opened 2023-01-04 20:01 UTC by groybal

…sing Java 11

##### Checklist

-   [X] the [individual contributor license agreement][] is signed
-   [X] commit message follows [commit guidelines][]

##### Description of change

Updated how files are used in Gradle scripts in order to avoid issue where Gradle uses current-working-directory (CWD) that is not the project directory, and problems can arise when files are then not found.  This issue was found when testing with Java 11, and the issue caused portal.home to be set to the wrong directory.
See:  https://docs.gradle.org/current/userguide/working_with_files.html#sec:single_file_paths

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

2023-01-06 17:30 UTC, ChristianMurphy requested changes
Thanks @groybal!
Have you had a chance to check out the CI failure? It seems to point to missing properties on some of the variables.

2023-01-06 19:46 UTC, groybal commented on overlays/uPortal/build.gradle
> +        File skinListFile = newProject.file("${projectDir}/src/main/webapp/media/skins/respondr/skinList.xml")
Doh! dumb error, fixed now.

2023-01-06 20:32 UTC, ChristianMurphy approved these changes

2023-01-11 21:24 UTC, bjagg approved these changes
Looks great!

2023-01-11 21:24 UTC, merged